version: "3"
services:
  databases:
    image: ${DATABASE_IMAGE}
    container_name: simbioff-database
    restart: always
    ports:
      - "5441:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
